import Foundation
import CoreData


extension Appointment {

    /// unique identifier for entity (generated by server)
    @NSManaged public var appointmentID: String
    /// expected end time
    @NSManaged public var scheduledEnd: Date?
    /// expected start time
    @NSManaged public var scheduledStart: Date?
    /// opaque version tag (generated by server)
    @NSManaged public var etag: String?
    /// name of patient who is the focus of appointment
    @NSManaged public var patientName: String?
    /// any additional notes
    @NSManaged public var notes: String?

    // MARK: Relationships

    /// Audio recordings created during appointment
    @NSManaged public var recordings: NSSet?/*<Recording>*/
    /// Data indicating publish is pending
    @NSManaged public var pendingItem: PendingItem?

}

// MARK: Generated accessors for recordings
extension Appointment {

    @objc(addRecordingsObject:)
    @NSManaged public func addToRecordings(_ value: Recording)

    @objc(removeRecordingsObject:)
    @NSManaged public func removeFromRecordings(_ value: Recording)

    @objc(addRecordings:)
    @NSManaged public func addToRecordings(_ values: NSSet)

    @objc(removeRecordings:)
    @NSManaged public func removeFromRecordings(_ values: NSSet)

}
