import Foundation
import CoreData


extension Recording {

    // MARK: Properties

    /// unique identifier for entity (generated by server)
    @NSManaged public var recordingID: String
    /// unique identifier for parent entity
    @NSManaged public var appointmentID: String
    /// duration of recording, in seconds
    @NSManaged public var duration: TimeInterval
    /// time when recording ended
    @NSManaged public var end: Date?
    /// time when recording began
    @NSManaged public var start: Date?
    /// opaque version tag (generated by server)
    @NSManaged public var etag: String?
    /// URL where audio data can be downloaded (generated by server)
    @NSManaged public var streamingURL: String?
    /// Local audio data ready to upload to server if needed
    @NSManaged public var audioData: Data?

    // MARK: Relationships

    /// Parent entity
    @NSManaged public var appointment: Appointment?
    /// Data indicating publish is pending
    @NSManaged public var pendingItem: PendingItem?

}
