import CoreData

extension Appointment {
    /// Establish relationships for entity
    func setUpRelationships(
        json: JSONAppointment,
        moc: NSManagedObjectContext
    ) {
        // since ID can change (we create a temp one,
        // the real one is generated by server),
        // keep related entities up-to-date
        for recording in self.recordings ?? [] {
            (recording as? Recording)?.appointmentID = self.id
        }

        let recordings = try? Recording.all(matching: .appointmentID(id), moc: moc)
        self.recordings = NSSet(array: recordings ?? [])
    }
}
